### ISSUE TITLE
Bad part on schematic_1v4.pdf

### ISSUE THREAD

**Issue by rujorgensen** [espruino/EspruinoBoard#11]
Just wanted to let you know that I stumbled over a part on the schematic of the **Espruino Pico, v 1.4**, that I think is wrong 🙂.

The part is connected to pin P7 (NRST pin). It's called "**R2**", has the symbol of a capacitor, and the value "**100k**". 

I have read part of the datasheet, and I think the value should be changed to "**100 nF**", and it's designator should probably be changed to "**C7**" (or "C9" if the load caps of the 8 MHz crystal has hidden designators).

**Comment by gfwilliams** [comment]
Hi - thanks, but it's definitely a resistor.

Not sure why it was showing as a capacitor though. I have now fixed the schematic

**Comment by rujorgensen** [comment]
Yeah, I digged a little deeper into it and figured that too 🙂. Perhaps the capacitor in the recommended design is acting as debounce cap. for the button.

In any case; section 6.3.17 in the [datasheet ](https://www.espruino.com/datasheets/STM32F401xD.pdf) states that NRST "... is connected to a permanent pull-up resistor" internally (40k typical ). Just wanted to make sure you knew in case you missed it--but perhaps you have good reasons for the external 100k 😊.

**Comment by rujorgensen** [comment]
Oh, and happy to hear you made the fix of course--the work you put into this project is stunning 😊👍.
