### ISSUE TITLE
P0.09/NFC1 capacitor not connected to ground?

### ISSUE THREAD

**Issue by bettse** [espruino/EspruinoBoard#12]
I'm a software guy, so please take this with a grain of salt.  I was looking over the board and noticed that the P0.10/NFC2 capacitor has a blue line to the big ground pad, but the P0.09/NFC1 capacitor doesn't.  I have no idea if this is just a 'typo' in the documentation or what, but I figured I'd mention it.
<img width="862" alt="yellow arrow" src="https://user-images.githubusercontent.com/115752/126025168-3231a28d-88b2-479f-ba0a-c58ba9d9e604.png">

**Comment by gfwilliams** [comment]
Thanks! yeah, that's actually fine though. It's connected in the schematic.

There's actually an automatic fill that's put on by eagle (inside the dotted rectangle) that fills and connects all 'empty' areas with ground - so that'll automatically connect up that capacitor :)
