### ISSUE TITLE
Eagle files for pico board?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [espruino/EspruinoBoard#6]
Hi Guys.

Are the eagle files for the Pico and other boards in the repo somewhere? as I can't find them

**Comment by gfwilliams** [comment]
Hi Roger,

The original Espruino board is [here](https://github.com/espruino/EspruinoBoard/tree/master/eagle) however I'm in the process of making the Pico rev 1.4, so was holding off putting the files online until I was sure that those were final.

To be honest I probably should have put the rev 1.3 online though, I'll do that now.

**Comment by gfwilliams** [comment]
Ok, just moved things around - rev 1v3 is now here: 

https://github.com/espruino/EspruinoBoard/tree/master/Pico/eagle

**Comment by rogerclarkmelbourne** [comment]
Gordon
Thanks thats great news.

Can you post to this issue when 1.4 is available as then I'd get a notification

**Comment by gfwilliams** [comment]
Ok, I'll try and remember. Layout is a bit different, but the only real schematic change will be the addition of a fuse.
